name: create pdfs and pngs

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Which document should be generated?'
        type: string
        required: true
        default: "report"

jobs:
  build:
    name: Document ${{ github.event.inputs.subject }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "main"

      - uses: matthejue/texlive-action-personal-copy/full@master
        with:
          run: |
            cd ./${{ github.event.inputs.subject }}
            latexmk main.tex
            mv main.pdf ${{ github.event.inputs.subject }}.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.subject }}
          path: ./${{ github.event.inputs.subject }}/${{ github.event.inputs.subject }}.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.subject }}
          path: ./${{ github.event.inputs.subject }}

      - name: Create Tag
        id: tag
        run: |
          TAG="${{ github.event.inputs.subject }}-$(date +'%Y%m%d-%H%M%S')"
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          files: |
            ./${{ github.event.inputs.subject }}/${{ github.event.inputs.subject }}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
